In [178]:
import numpy as np
np.set_printoptions(formatter={'float': lambda x: "{0:0.10f}".format(x)})

In [179]:
inRGB = np.array([191, 0, 0])
print("Input RGB: ", inRGB)

Input RGB:  [191   0   0]


In [184]:
# Constants here!
yuvToRGB709 = np.array( [
    [1.1644, 0.0, 1.7927],
    [1.1644, -0.2132, -0.5329],
    [1.1644, 2.1124, 0.0]
])

rgbToYUV709 = np.linalg.inv(np.array([
    [1.1644, 0.0, 1.7927],
    [1.1644, -0.2132, -0.5329],
    [1.1644, 2.1124, 0.0]
]))

print("YUV matrix should be: \n", np.transpose(rgbToYUV709))

rangeScale = (235.0 - 16.0) / (255.0 - 0.0)
rangeScalePerChannel = np.array([rangeScale, rangeScale, rangeScale])
yuvOffset = np.array([16.0, 128.0, 128.0])

YUV matrix should be: 
 [[0.1825870759 -0.1006458962 0.4392232994]
 [0.6142312835 -0.3385774032 -0.3989573863]
 [0.0619930457 0.4392232994 -0.0402659131]]


In [181]:
yuvLegal = np.matmul(rgbToYUV7092, inRGB) + np.array([16.0, 128.0, 128.0])

print("RGB source -> ", inRGB, ", in YUV -> ", yuvLegal)

RGB source ->  [191   0   0] , in YUV ->  [50.8741314962 108.7766338221 211.8916501845]


In [182]:
yuvOffset = np.array([-16.0, -128.0, -128.0])
yuvWithOffset = yuvLegal + yuvOffset
outRGB = np.matmul(yuvToRGB709, yuvWithOffset)
print("Resulting RGB: ", outRGB)

Resulting RGB:  [191.0000000000 0.0000000000 -0.0000000000]
